---
title: "predicting ncaa basketbal rank"
output: pdf_document
---

### code provided in class sessions
```{r}
# 1. load the data
games <- read.csv("http://www.stanford.edu/~wfithian/games.csv",as.is=TRUE)
teams <- read.csv("http://www.stanford.edu/~wfithian/teams.csv",as.is=TRUE)

all.teams <- sort(unique(c(teams$team,games$home,games$away)))

# 2. rank teams

total.margin <- function(team) {
  with(games,
       sum(homeScore[home==team]) 
       + sum(awayScore[away==team]) 
       - sum(homeScore[away==team])  
       - sum(awayScore[home==team]))
}

margins <- sapply(teams$team, total.margin)
names(margins) <- teams$team

raw.rank.table <- cbind("Margin"      = margins,
                    "Margin Rank" = rank(-margins,ties="min"),
                    "AP Rank"     = teams$apRank,
                    "USAT Rank"   = teams$usaTodayRank)

margin.top25 <- order(margins,decreasing=TRUE)[1:25]
raw.rank.table[margin.top25,]

# 2. linear ranking

## a. build x and y 

### i. trying to predict the net score for each game,...
y <- with(games, homeScore-awayScore)

### ii. ...using an indicator for whether the team played at home (1) or away(-1)
X0 <- as.data.frame(matrix(0,nrow(games),length(all.teams)))
names(X0) <- all.teams
for(tm in all.teams) {
  X0[[tm]] <- 1*(games$home==tm) - 1*(games$away==tm)
}

### iii. make stanford the baseline for which point scores relative

X <- X0[,names(X0) != "stanford-cardinal"]
reg.season.games <- which(games$gameType=="REG")

mod <- lm(y ~ 0 + ., data=X, subset=reg.season.games)
head(coef(summary(mod)))
summary(mod)$r.squared
coef(mod)["`alabama-crimson-tide`"] - coef(mod)["`air-force-falcons`"]

### d. encode home court advantage

homeAdv <- 1 - games$neutralLocation
homeAdv.mod <- lm(y ~ 0 + homeAdv + ., data=X, subset=reg.season.games)
homeAdv.coef <- coef(homeAdv.mod)[paste("`",teams$team,"`",sep="")]
names(homeAdv.coef) <- teams$team

head(coef(summary(homeAdv.mod)))

homeAdv.estimate <- coef(homeAdv.mod)["homeAdv"]
homeAdv.se <- coef(summary(homeAdv.mod))["homeAdv",2]
(homeAdv.CI <- c("CI Lower"=homeAdv.estimate - 2*homeAdv.se,
                 "CI Upper"=homeAdv.estimate + 2*homeAdv.se))

### e. predict wins, losses

resids <- homeAdv.mod$resid
par(mfrow=c(1,2))
hist(resids,freq=FALSE)
curve(dnorm(x,mean(resids),sd(resids)),add=TRUE,col="blue",lwd=2)
qqnorm(resids)

schedule <- function(team, game.type) {
  home.sch <- with(games, games[home==team & gameType==game.type,c(1,3,4,5)])
  away.sch <- with(games, games[away==team & gameType==game.type,c(1,2,5,4)])
  names(home.sch) <- names(away.sch) <- c("date","opponent","score","oppoScore")
  sch <- rbind(home.sch,away.sch)
  
  sch$margin <- with(sch, score-oppoScore)
  sch$oppoQuality <- homeAdv.coef[as.character(sch$opponent)]
  
  sch <- sch[order(sch$date),]
  rownames(sch) <- NULL
  return(sch)
}
schedule("wichita-state-shockers","NCAA")

(sigma <- sd(resids))

mu <- coef(homeAdv.mod)["homeAdv"] + coef(homeAdv.mod)["`california-golden-bears`"] - 0
pnorm(-mu/sigma)

wst.schedule <- schedule("wichita-state-shockers","NCAA")
mu <- wst.schedule$oppoQuality - homeAdv.coef["wichita-state-shockers"]
names(mu) <- wst.schedule$opponent
(p.wst.win <- pnorm(-mu/sigma))

prod(p.wst.win[1:4])

lou.schedule <- schedule("louisville-cardinals","NCAA")
mu <- lou.schedule$oppoQuality - homeAdv.coef["louisville-cardinals"]
prod(pnorm(-mu/sigma))

### f. model vs. official ranks

rank.table <- cbind("Model Score" = homeAdv.coef,
                    "Model Rank"  = rank(-homeAdv.coef,ties="min"),
                    "AP Rank"     = teams$apRank,
                    "USAT Rank"   = teams$usaTodayRank)
rank.table[order(homeAdv.coef,decreasing=TRUE)[1:25],]

par(mfrow=c(1,1))
hist(schedule("miami-(fl)-hurricanes", "REG")$margin,
     col="gray",border="gray",breaks=seq(-20,50,5), 
     xlab="Margin of Victory",
     main="Margins of Victory for Miami (gray) and Florida (red)",)
hist(schedule("florida-gators", "REG")$margin,add=TRUE,
     border="red",breaks=seq(-20,50,5),col="red",density=20)
abline(v=0)

mean(schedule("miami-(fl)-hurricanes", "REG")$oppoQuality)

mean(schedule("florida-gators", "REG")$oppoQuality)

### g. nerlens' value

nerlens <- rep(0,nrow(games))
nerlens[games$home=="kentucky-wildcats" & games$date<"2013-02-12"] <- 1
nerlens[games$away=="kentucky-wildcats" & games$date<"2013-02-12"] <- -1
nerlens.mod <- lm(y ~ 0 + homeAdv + nerlens + ., data=X, subset=reg.season.games)
head(coef(summary(nerlens.mod)))

nerlens.estimate <- coef(nerlens.mod)["nerlens"]
nerlens.se <- coef(summary(nerlens.mod))["nerlens",2]
(nerlens.CI <- c("CI lower"=nerlens.estimate - 2*nerlens.se,
                 "CI upper"=nerlens.estimate + 2*nerlens.se))

coef(nerlens.mod)[c("nerlens","`kentucky-wildcats`")]

```

### problem 4a
```{r}
y.lr=rep(0,dim(games)[1]); y.lr[y>0]=1

lr.mod=glm(y.lr~0+homeAdv+.,data=X,subset=reg.season.games,family=binomial)
lr.coef = coef(lr.mod)[paste("`",teams$team,"`",sep="")]
names(lr.coef) = teams$team
head(coef(summary(lr.mod)))

games[games$home=="saint-mary-saint-mary" | 
           games$away=="saint-mary-saint-mary",]
games[games$home=="st.-thomas-(tx)-celts" | 
           games$away=="st.-thomas-(tx)-celts",]
```

### problem 4b
```{r}
# remove columns of teams w/ < regular season 5 games
greater.5=NULL
keep=1
for(cols in 1:length(X)){
     if(sum(X[reg.season.games,cols]!=0)>=5){
          greater.5[keep]=cols
          keep=keep+1
     }
}
X5=X[,greater.5]

# run logistic regresson
lr.mod=glm(y.lr~0+homeAdv+.,data=X5,subset=reg.season.games,family=binomial)
lr.coef = coef(lr.mod)[paste("`",teams$team,"`",sep="")]
names(lr.coef) = teams$team
head(coef(summary(lr.mod)))

# rank teams on logistic result
lr.rank.table <- cbind("Model Score" = lr.coef,
                    "Logistic Rank"  = rank(-lr.coef,ties="min"),
                    "Linear Rank" = rank.table[,2],
                    "AP Rank"     = teams$apRank,
                    "USAT Rank"   = teams$usaTodayRank)
lr.rank.table[order(lr.coef,decreasing=TRUE)[1:25],]

```

### problem 4c
```{r}

sum(coef(summary(homeAdv.mod))[,4]<=0.05)/dim(coef(summary(homeAdv.mod)))[1]
sum(coef(summary(lr.mod))[,4]<=0.05)/dim(coef(summary(lr.mod)))[1]

```

### problem 4d
```{r}

# predict / score
## cross validation
set.seed(4)
folds = 1:10

cvdata.x = cbind(homeAdv,X5)
y.ln=rep(0,length(y));y.ln[y>0]=1
foldid = sample(rep(folds, length=dim(cvdata.x)[1]))
foldid[1:9]
table(foldid)

one.fold <- function(leaveout){
     print(leaveout)
     # linear
     test.x = cvdata.x[foldid==leaveout,]
     train.x = cvdata.x[foldid!=leaveout,]
     
     test.y.ln = y.ln[foldid==leaveout]
     train.y.ln = y[foldid!=leaveout]
     
     fit.ln = lm(train.y.ln ~ ., data=train.x, subset=reg.season.games)

     points.ln = predict(fit.ln,test.x)
     pred.ln = rep(0,length(test.y.ln)); pred.ln[points.ln>0.0]=1
     
     # logistic
     test.x = cvdata.x[foldid==leaveout,]
     train.x = cvdata.x[foldid!=leaveout,]
     
     test.y.lr = y.lr[foldid==leaveout]
     train.y.lr = y.lr[foldid!=leaveout]

     fit.lr = glm(train.y.lr ~ ., data=train.x ,subset=reg.season.games,
                  family=binomial)

     probs.lr = predict(fit.lr,test.x,type="response")
     pred.lr=rep(0,length(test.y.lr)); pred.lr[probs.lr>0.5]=1
     
     # score both
     score.ln = rep(0,length(test.y.lr));score.ln[pred.ln==test.y.lr]=1
     score.lr = rep(0,length(test.y.lr));score.lr[pred.lr==test.y.lr]=1
     result = table(score.ln,score.lr)
     print(result)
}

cv.errs <- sapply(folds, one.fold)

result=matrix(NA,2,2)
colnames(result)=c("logistic right", "logistic wrong")
rownames(result)=c("linear right", "linear wrong")
result[1,1]=rowSums(cv.errs)[4]
result[2,2]=rowSums(cv.errs)[1]
ln.right=result[1,2]=rowSums(cv.errs)[2]
lr.right=result[2,1]=rowSums(cv.errs)[3]
print(result)

```

### problem 4e
```{r}
# per mean and standard deviation in question stem
D=ln.right+lr.right
mu_d=D/2
sd_d=sqrt(D)/2

pnorm(ln.right,mean=mu_d,sd=sd_d,lower.tail=F)
pnorm(lr.right,mean=mu_d,sd=sd_d,lower.tail=F)

# per mean and standard deviation from cross validation
mu_d=mean(cv.errs[2,]+cv.errs[3])/2
sd_d=sd(cv.errs[2,]+cv.errs[3])

pnorm(ln.right/dim(cv.errs)[2],mean=mu_d,sd=sd_d,lower.tail=F)
pnorm(lr.right/dim(cv.errs)[2],mean=mu_d,sd=sd_d,lower.tail=F)

```